### PR TITLE
Add suport for ndx-beadl to conversion code

### PR DESCRIPTION
**Pull request by oruebel**

### CODE REVIEW

**Comment by oruebel** [comment]
Sorry for the erroneous PR. I was just playing around with adding support for the ndx-beadl extension in the conversion on a fork.

**Comment by chenxinfeng4** [comment]
Thanks for your interest. If you have good idea, feel free to give a PR.

**Comment by oruebel** [comment]
> If you have good idea, feel free to give a PR.

Will do. The main idea is to optionally allow the use of the ndx-beadl extension to make the data easier to use in NWB. However, the changes were not complete yet when I opened the PR. 

Quick question, does ArControl store information about the start and end of trials in the output?

**Comment by chenxinfeng4** [comment]
The **"start trial"** is always the first "C1S1" at exact the 00:00:00.000 sec.
The **"end trial"** depends on when you "terminate" the task recording. 1. If you "terminate" by GUI STOP button, the end trials is not  recorded. You should manually read the last event tick to GUESS. 2. If you "terminate" by Designer->GoState->"endup", the end time tick is "C0S0".

**Comment by oruebel** [comment]
Thanks!

**Comment by chenxinfeng4** [comment]
I saw your code revision. You've done very nice code comments and polishing. 

I saw you are trying to get the ndx-beadl feature. I tried but failed to implant the ndx-beadl feature. I even can't have a beadl system in my hand, nor do I understand how a "sweep" or "trial" was defined in beadl and ndx. It would be nice if you can do the ndx-beadl adaptation, so the community can have more standard behavioral data.

**Comment by oruebel** [comment]
> The **"end trial"** depends on when you "terminate" the task recording.

Just to clarify, does this mean the stop of trial in ARControl is defined by the user terminating the program, i.e, is there always just one-trial per ARControl output, or is there logic in the state-machine such that the subject can initiate a new trial? 

> how a "sweep" or "trial" was defined in beadl and ndx

NWB defines a trial broadly as  "Repeated experimental events that have a logical grouping." The actual logic for grouping is up to the user. In BEADL the definition of trials is part of the output and the logic for the begin and end of a trial is (as far as I know) part of the state-machine logic of the behavioral task program. 

> It would be nice if you can do the ndx-beadl adaptation, so the community can have more standard behavioral data.

I will circle back to this in 2 weeks, but am happy to contribute this back to the repo once I'm done. The main parts I'm missing right now are the trials and task parameters.

Do you by chance have the XML of the ARControl program that was used for the example data in the [playground](https://github.com/chenxinfeng4/ArControl-convert2-nwb/tree/main/playground) folder (or have some other example data I could use. The ndx-beadl extension allows us to store the XML in NWB and I ideally also would like to extract main parameters of the task program for the TaskParameters table in the extension. Also, does ARControl define an XML schema (XSD file) for the XML task program?

**Comment by chenxinfeng4** [comment]
> The "end trial" depends on when you "terminate" the task recording.

To clarify, the ArControl task is not "trial" based programming, but it's "State Machine" based. The "Component", which is a collection of States, is most close to the concept of a trial. The "trial" is logical for user, the "Component/State" is for computer. So, I can tell which is "end trial", but I can tell which is the "end Component/State". Sometimes, user may terminate a recording in the middle of a trial. So the "end State" may not match the "end of trial".

> how a "sweep" or "trial" was defined in beadl and ndx.  .... The actual logic for grouping is up to the user. 

The ArControl task is "State Machine" based. The "sweep" or "trial" processing would ask user to manually programing. So I hope the "sweep/trial" processing can be separated in another script file.

> Do you by chance have the XML of the ARControl program

I've no behavior data in my hand. ArControl .txt data didn't contain `task_schema` information, you should watch the task/xxx/`*.aconf` file, which is XML format. To parse/convert a ArControl task, it's a good start point to see [ArControl-convert2-smcat](https://github.com/chenxinfeng4/ArControl-convert2-smcat). That code is simply done by python.

**Comment by oruebel** [comment]
> To clarify, the ArControl task is not "trial" based programming, but it's "State Machine" based.

Yes, BEADL is state-machine-based as well. 

> The "Component", which is a collection of States, is most close to the concept of a trial.

That makes sense. Mapping components to trials seems reasonable.

**Comment by chenxinfeng4** [comment]
> BEADL is state-machine-based as well.

 The BEADL  may be instructive for the "trial" definition. But I didn't have the BEADL software yet.

**Pull request closed without merging**
